In [ ]:
import pandas as pd
headers = ["ID","CT","UCSize","UCShape","MA","SECSize","BN","BC","NN","Mitoses","Diagnosis"]
data = pd.read_csv('breast-cancer-wisconsin.data', na_values='?',    
         header=None, index_col=['ID'], names = headers) 
data = data.reset_index(drop=True)
data = data.fillna(0)
data.describe()

CT      UCSize     UCShape  ...          NN     Mitoses   Diagnosis
count  699.000000  699.000000  699.000000  ...  699.000000  699.000000  699.000000
mean     4.417740    3.134478    3.207439  ...    2.866953    1.589413    2.689557
std      2.815741    3.051459    2.971913  ...    3.053634    1.715078    0.951273
min      1.000000    1.000000    1.000000  ...    1.000000    1.000000    2.000000
25%      2.000000    1.000000    1.000000  ...    1.000000    1.000000    2.000000
50%      4.000000    1.000000    1.000000  ...    1.000000    1.000000    2.000000
75%      6.000000    5.000000    5.000000  ...    4.000000    1.000000    4.000000
max     10.000000   10.000000   10.000000  ...   10.000000   10.000000    4.000000

[8 rows x 10 columns]

In [ ]:
data

CT  UCSize  UCShape  MA  SECSize    BN  BC  NN  Mitoses  Diagnosis
0     5       1        1   1        2   1.0   3   1        1          2
1     5       4        4   5        7  10.0   3   2        1          2
2     3       1        1   1        2   2.0   3   1        1          2
3     6       8        8   1        3   4.0   3   7        1          2
4     4       1        1   3        2   1.0   3   1        1          2
..   ..     ...      ...  ..      ...   ...  ..  ..      ...        ...
694   3       1        1   1        3   2.0   1   1        1          2
695   2       1        1   1        2   1.0   1   1        1          2
696   5      10       10   3        7   3.0   8  10        2          4
697   4       8        6   4        3   4.0  10   6        1          4
698   4       8        8   5        4   5.0  10   4        1          4

[699 rows x 10 columns]

In [ ]:
dfx=data.iloc[:,0:9]
dfx

CT  UCSize  UCShape  MA  SECSize    BN  BC  NN  Mitoses
0     5       1        1   1        2   1.0   3   1        1
1     5       4        4   5        7  10.0   3   2        1
2     3       1        1   1        2   2.0   3   1        1
3     6       8        8   1        3   4.0   3   7        1
4     4       1        1   3        2   1.0   3   1        1
..   ..     ...      ...  ..      ...   ...  ..  ..      ...
694   3       1        1   1        3   2.0   1   1        1
695   2       1        1   1        2   1.0   1   1        1
696   5      10       10   3        7   3.0   8  10        2
697   4       8        6   4        3   4.0  10   6        1
698   4       8        8   5        4   5.0  10   4        1

[699 rows x 9 columns]

In [ ]:
dfy=data.iloc[:,[9]]
dfy

Diagnosis
0            2
1            2
2            2
3            2
4            2
..         ...
694          2
695          2
696          4
697          4
698          4

[699 rows x 1 columns]

In [ ]:
import numpy as np
X=dfx.to_numpy()
y=dfy.to_numpy()

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
print(X_train)

[[ 5.  2.  1. ...  3.  1.  1.]
 [ 5.  3.  3. ...  3.  4.  1.]
 [ 1.  1.  1. ...  3.  1.  1.]
 ...
 [ 8.  4.  7. ...  3.  9.  2.]
 [10.  8. 10. ...  5.  1.  1.]
 [ 4.  1.  2. ...  3.  1.  1.]]


In [ ]:
X_train.shape

(559, 9)

In [ ]:
import math

In [ ]:
class Node:
  def __init__(self,predicted_class,genie,Entropy):
    self.prediction=predicted_class
    self.Entropy=1
    self.genie=1
    self.col_idx=0
    self.threshold=0
    self.left=None
    self.right=None

def fit(X,y,max_depth,split_metric):
  tree=make_tree(X,y,0,max_depth,split_metric)
  return tree
def Entropy_parent(left):
  if left[0]==0 or left[1]==0:
    return 0
  total_left=left[0]+left[1]
  if total_left==0:
    return 0
  Eleft=0-((float(left[0])/total_left)*math.log2(float(left[0])/total_left)+(float(left[1])/total_left)*math.log2(float(left[1])/total_left))
  return Eleft

def Entropy(left,right):
  total_left=left[0]+left[1]
  total_right=right[0]+right[1]
  if left[0]==0 or left[1]==0:
    if right[0]==0 or right[1]==0:
      return 0
    else:
      Eright=0-((float(right[0])/total_right)*math.log2(float(right[0])/total_right)+(float(right[1])/total_right)*math.log2(float(right[1])/total_right))
      return Eright
  if right[0]==0 or right[1]==0:
    if left[0]==0 or left[1]==0:
      return 0
    else:
      Eleft=0-((float(left[0])/total_left)*math.log2(float(left[0])/total_left)+(float(left[1])/total_left)*math.log2(float(left[1])/total_left))
      return Eleft
  Eleft=0-((float(left[0])/total_left)*math.log2(float(left[0])/total_left)+(float(left[1])/total_left)*math.log2(float(left[1])/total_left))
  if total_right==0:
    return gleft
  Eright=0-((float(right[0])/total_right)*math.log2(float(right[0])/total_right)+(float(right[1])/total_right)*math.log2(float(right[1])/total_right))
  total=total_left+total_right
  E=(float(total_left)/total)*Eleft+(float(total_right)/total)*Eright
  return E
def make_tree(X,y,depth,max_depth,split_metric):
  nfeatures=X.shape[1]
  classes=[2,4]
  number_of_elements=[]
  for ele in classes:
    count=0
    for i in range(len(y)):
      if y[i]==ele:
        count+=1
    number_of_elements.append(count)
    
  max=0
  index=0
  for i in range(len(number_of_elements)):
    if(number_of_elements[i]>max):
      max=number_of_elements[i]
      index=i
  g=0
  node=Node(classes[index],1,1)
  if split_metric=="genie":
    g=genie_parent(number_of_elements)
    node.genie=g
  elif split_metric=="Entropy":
    g=Entropy_parent(number_of_elements)
    node.Entropy=g
  
  if g==0.0:
      return node
  if depth<max_depth:
    thres,indx = best_split(X,y,nfeatures,split_metric)
    print("col_index:",indx,"thres:",thres)
    if indx!=None:
      left_indices=X[:,indx]<=thres
      right_indices=X[:,indx]>thres
      X_left,y_left=X[left_indices],y[left_indices]
      X_right,y_right=X[right_indices],y[right_indices]
      node.col_idx=indx
      node.threshold=thres
      #print("col_index:",indx,"thres:",thres)
      node.left=make_tree(X_left,y_left,depth+1,max_depth,split_metric)
      node.right=make_tree(X_right,y_right,depth+1,max_depth,split_metric)
  return node
def predictionHelper(ele,root):
  while root!=None:
    index=root.col_idx
    if ele[index]<=root.threshold:
      if root.left!=None:
        root=root.left
      else:
        return root.prediction
    else:
      if root.right!=None:
        root=root.right
      else:
        return root.prediction
def genie_parent(left):
  #print(left)
  total_left=left[0]+left[1]
  if total_left==0:
    return 0
  gleft=1-((float(left[0])/total_left)**2+(float(left[1])/total_left)**2)
  return gleft
def predict(X,root):
  result=[]
  for ele in X:
    result.append(predictionHelper(ele,root))
  return result
def genie(left,right):
  total_left=left[0]+left[1]
  total_right=right[0]+right[1]
  gleft=1-((float(left[0])/total_left)**2+(float(left[1])/total_left)**2)
  if total_right==0:
    return gleft
  gright=1-((float(right[0])/total_right)**2+(float(right[1])/total_right)**2)
  total=total_left+total_right
  g=(float(total_left)/total)*gleft+(float(total_right)/total)*gright
  return g
def best_split(X,y,numfeatures,split_metric):
  best_thres=0
  best_gen=9999
  best_feature=99
  for col in range(numfeatures):
    temp=[]
    class_ben=0 #2
    class_malig=0 #4
    for i in range(len(X)):
      x=[]      
      x.append(X[i][col])
      x.append(y[i])
      if y[i]==2:
        class_ben+=1
      temp.append(x)
    class_malig=len(temp)-class_ben
    left_tree=[0,0]
    right_tree=[class_ben,class_malig]
    temp.sort(key=lambda x:x[0])
    i=0
    while i <(len(temp)):
      thres=temp[i][0]
      while i<len(temp) and temp[i][0]==thres:
        if temp[i][1]==2:
          right_tree[0]-=1
          left_tree[0]+=1
        elif temp[i][1]==4:
          right_tree[1]-=1
          left_tree[1]+=1
        i+=1
      sm=0
      if split_metric=="genie": 
        sm=genie(left_tree,right_tree)
      elif split_metric=="Entropy":
        sm=Entropy(left_tree,right_tree)
      if sm<best_gen:
        best_gen=sm
        best_thres=thres
        best_feature=col
  return best_thres,best_feature



In [ ]:
rootg=fit(X_train,y_train,2,"genie")
hp=predict(X_test,rootg)
print(hp)
len(hp)

col_index: 2 thres: 3.0
col_index: 5 thres: 5.0
col_index: 5 thres: 1.0
[2, 2, 2, 4, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 4, 2, 4, 4, 4, 4, 2, 4, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 2, 2, 4, 2, 2, 2, 2, 4, 4, 2, 2, 2, 4, 2, 4, 4, 2, 4, 2, 2, 2, 2, 4, 2, 2, 2, 4, 4, 2, 2, 4, 2, 4, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 2, 2, 4, 4, 2, 4, 4, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 2, 2, 4, 2, 2, 2, 4, 2, 4, 2, 4, 2, 2, 2]


140

In [ ]:
num_test=len(y_test)
num_correct=0
for i in range(num_test):
  if y_test[i]==hp[i]:
    num_correct+=1
accuracy = float(num_correct) / num_test
print('Got %d / %d correct => accuracy: %f' % (num_correct, num_test, accuracy))

Got 131 / 140 correct => accuracy: 0.935714


In [ ]:
roote=fit(X_train,y_train,3,"Entropy")
hp=predict(X_test,roote)
print(hp)
len(hp)

col_index: 1 thres: 2.0
col_index: 5 thres: 2.0
col_index: 7 thres: 3.0
col_index: 0 thres: 4.0
col_index: 1 thres: 4.0
col_index: 5 thres: 3.0
col_index: 5 thres: 0.0
[2, 2, 2, 4, 2, 2, 2, 4, 4, 2, 2, 4, 2, 2, 2, 4, 2, 4, 4, 2, 4, 2, 4, 2, 4, 2, 2, 4, 4, 4, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 4, 2, 2, 2, 2, 4, 2, 2, 2, 4, 4, 2, 2, 4, 2, 4, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 2, 2, 4, 4, 2, 2, 4, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 2, 2, 4, 2, 2, 2, 4, 2, 4, 2, 4, 2, 2, 2]


140

In [ ]:
num_test=len(y_test)
num_correct=0
for i in range(num_test):
  if y_test[i]==hp[i]:
    num_correct+=1
accuracy = float(num_correct) / num_test
print('Got %d / %d correct => accuracy: %f' % (num_correct, num_test, accuracy))

Got 131 / 140 correct => accuracy: 0.935714


In [ ]:
#headers
# class Node:
#   def __init__(self,predicted_class,genie,Entropy):
#     self.prediction=predicted_class
#     self.Entropy=1
#     self.genie=1
#     self.col_idx=0
#     self.threshold=0
#     self.left=None
#     self.right=None
def get_DFS(tree,tab_space):

  if tree.left == None and tree.right==None:
    return tab_space + str(tree.prediction)

  question=headers[tree.col_idx]
  statement=tab_space+'Is ' + question + '?\n'
  left_side=tree.left
  right_side=tree.right
  if left_side:
    statement+=tab_space+'True Branch\n'
    new_tab=tab_space+' '
    statement+=get_DFS(left_side,new_tab)
  if right_side:
    statement+=tab_space+'False Branch\n'
    new_tab=tab_space+' '
    statement+=get_DFS(right_side,new_tab)
  return statement
def DFS(node):
  tab_space=''
  #pprint(self.tree)
  statement=get_DFS(node,tab_space)
  print(statement)
DFS()

Is CT?
True Branch
 Is SECSize?
 True Branch
  Is BC?
  True Branch
   2  False Branch
   4 False Branch
  Is ID?
  True Branch
   2  False Branch
   4False Branch
 Is CT?
 True Branch
  Is SECSize?
  True Branch
   2  False Branch
   4 False Branch
  Is SECSize?
  True Branch
   2  False Branch
   4
