In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sb

In [ ]:
df=pd.read_csv("diamonds.csv")
df

carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [ ]:
le=LabelEncoder()
df['cut1']=le.fit_transform(df['cut'])

In [ ]:
df

carat        cut color clarity  depth  ...  price     x     y     z  cut1
0       0.23      Ideal     E     SI2   61.5  ...    326  3.95  3.98  2.43     2
1       0.21    Premium     E     SI1   59.8  ...    326  3.89  3.84  2.31     3
2       0.23       Good     E     VS1   56.9  ...    327  4.05  4.07  2.31     1
3       0.29    Premium     I     VS2   62.4  ...    334  4.20  4.23  2.63     3
4       0.31       Good     J     SI2   63.3  ...    335  4.34  4.35  2.75     1
...      ...        ...   ...     ...    ...  ...    ...   ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8  ...   2757  5.75  5.76  3.50     2
53936   0.72       Good     D     SI1   63.1  ...   2757  5.69  5.75  3.61     1
53937   0.70  Very Good     D     SI1   62.8  ...   2757  5.66  5.68  3.56     4
53938   0.86    Premium     H     SI2   61.0  ...   2757  6.15  6.12  3.74     3
53939   0.75      Ideal     D     SI2   62.2  ...   2757  5.83  5.87  3.64     2

[53940 rows x 11 columns]

In [ ]:
df=df.drop('cut',axis=1)

In [ ]:

df.rename(columns = {'cut1':'cut'}, inplace = True)
df

carat color clarity  depth  table  price     x     y     z  cut
0       0.23     E     SI2   61.5   55.0    326  3.95  3.98  2.43    2
1       0.21     E     SI1   59.8   61.0    326  3.89  3.84  2.31    3
2       0.23     E     VS1   56.9   65.0    327  4.05  4.07  2.31    1
3       0.29     I     VS2   62.4   58.0    334  4.20  4.23  2.63    3
4       0.31     J     SI2   63.3   58.0    335  4.34  4.35  2.75    1
...      ...   ...     ...    ...    ...    ...   ...   ...   ...  ...
53935   0.72     D     SI1   60.8   57.0   2757  5.75  5.76  3.50    2
53936   0.72     D     SI1   63.1   55.0   2757  5.69  5.75  3.61    1
53937   0.70     D     SI1   62.8   60.0   2757  5.66  5.68  3.56    4
53938   0.86     H     SI2   61.0   58.0   2757  6.15  6.12  3.74    3
53939   0.75     D     SI2   62.2   55.0   2757  5.83  5.87  3.64    2

[53940 rows x 10 columns]

In [ ]:
df['color1']=le.fit_transform(df['color'])

In [ ]:
df=df.drop(['color'],axis=1)

In [ ]:
df


carat clarity  depth  table  price     x     y     z  cut  color1
0       0.23     SI2   61.5   55.0    326  3.95  3.98  2.43    2       1
1       0.21     SI1   59.8   61.0    326  3.89  3.84  2.31    3       1
2       0.23     VS1   56.9   65.0    327  4.05  4.07  2.31    1       1
3       0.29     VS2   62.4   58.0    334  4.20  4.23  2.63    3       5
4       0.31     SI2   63.3   58.0    335  4.34  4.35  2.75    1       6
...      ...     ...    ...    ...    ...   ...   ...   ...  ...     ...
53935   0.72     SI1   60.8   57.0   2757  5.75  5.76  3.50    2       0
53936   0.72     SI1   63.1   55.0   2757  5.69  5.75  3.61    1       0
53937   0.70     SI1   62.8   60.0   2757  5.66  5.68  3.56    4       0
53938   0.86     SI2   61.0   58.0   2757  6.15  6.12  3.74    3       4
53939   0.75     SI2   62.2   55.0   2757  5.83  5.87  3.64    2       0

[53940 rows x 10 columns]

In [ ]:
df['clarity1']=le.fit_transform(df['clarity'])
df=df.drop(['clarity'],axis=1)

In [ ]:
df

carat  depth  table  price     x     y     z  cut  color1  clarity1
0       0.23   61.5   55.0    326  3.95  3.98  2.43    2       1         3
1       0.21   59.8   61.0    326  3.89  3.84  2.31    3       1         2
2       0.23   56.9   65.0    327  4.05  4.07  2.31    1       1         4
3       0.29   62.4   58.0    334  4.20  4.23  2.63    3       5         5
4       0.31   63.3   58.0    335  4.34  4.35  2.75    1       6         3
...      ...    ...    ...    ...   ...   ...   ...  ...     ...       ...
53935   0.72   60.8   57.0   2757  5.75  5.76  3.50    2       0         2
53936   0.72   63.1   55.0   2757  5.69  5.75  3.61    1       0         2
53937   0.70   62.8   60.0   2757  5.66  5.68  3.56    4       0         2
53938   0.86   61.0   58.0   2757  6.15  6.12  3.74    3       4         3
53939   0.75   62.2   55.0   2757  5.83  5.87  3.64    2       0         3

[53940 rows x 10 columns]

In [ ]:
df.rename(columns = {'color1':'color'}, inplace = True)
df.rename(columns = {'clarity1':'clarity'}, inplace = True)

In [ ]:
df

carat  depth  table  price     x     y     z  cut  color  clarity
0       0.23   61.5   55.0    326  3.95  3.98  2.43    2      1        3
1       0.21   59.8   61.0    326  3.89  3.84  2.31    3      1        2
2       0.23   56.9   65.0    327  4.05  4.07  2.31    1      1        4
3       0.29   62.4   58.0    334  4.20  4.23  2.63    3      5        5
4       0.31   63.3   58.0    335  4.34  4.35  2.75    1      6        3
...      ...    ...    ...    ...   ...   ...   ...  ...    ...      ...
53935   0.72   60.8   57.0   2757  5.75  5.76  3.50    2      0        2
53936   0.72   63.1   55.0   2757  5.69  5.75  3.61    1      0        2
53937   0.70   62.8   60.0   2757  5.66  5.68  3.56    4      0        2
53938   0.86   61.0   58.0   2757  6.15  6.12  3.74    3      4        3
53939   0.75   62.2   55.0   2757  5.83  5.87  3.64    2      0        3

[53940 rows x 10 columns]

In [ ]:
dfx=df.iloc[:,[0,1,2,4,5,6,7,8,9]]
dfx

carat  depth  table     x     y     z  cut  color  clarity
0       0.23   61.5   55.0  3.95  3.98  2.43    2      1        3
1       0.21   59.8   61.0  3.89  3.84  2.31    3      1        2
2       0.23   56.9   65.0  4.05  4.07  2.31    1      1        4
3       0.29   62.4   58.0  4.20  4.23  2.63    3      5        5
4       0.31   63.3   58.0  4.34  4.35  2.75    1      6        3
...      ...    ...    ...   ...   ...   ...  ...    ...      ...
53935   0.72   60.8   57.0  5.75  5.76  3.50    2      0        2
53936   0.72   63.1   55.0  5.69  5.75  3.61    1      0        2
53937   0.70   62.8   60.0  5.66  5.68  3.56    4      0        2
53938   0.86   61.0   58.0  6.15  6.12  3.74    3      4        3
53939   0.75   62.2   55.0  5.83  5.87  3.64    2      0        3

[53940 rows x 9 columns]

In [ ]:
dfy=df.iloc[:,3]

In [ ]:
dfy

0         326
1         326
2         327
3         334
4         335
         ... 
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64

In [ ]:
dfx['carat1'] = (dfx['carat'] - dfx['carat'].mean())/dfx['carat'].std()
dfx['table1'] = (dfx['table'] - dfx['table'].mean())/dfx['table'].std()
dfx['x1'] = (dfx['x'] - dfx['x'].mean())/dfx['x'].std()
dfx['y1'] = (dfx['y'] - dfx['y'].mean())/dfx['y'].std()
dfx['z1'] = (dfx['z'] - dfx['z'].mean())/dfx['z'].std()
dfx['color1'] = (dfx['color'] - dfx['color'].mean())/dfx['color'].std()
dfx['clarity1'] = (dfx['clarity'] - dfx['clarity'].mean())/dfx['clarity'].std()
dfx['cut1'] = (dfx['cut'] - dfx['cut'].mean())/dfx['cut'].std()
dfx['depth1'] = (dfx['depth'] - dfx['depth'].mean())/dfx['depth'].std()


In [ ]:
dfx=dfx.drop('carat',1)
dfx=dfx.drop('table',1)
dfx=dfx.drop('x',1)
dfx=dfx.drop('y',1)
dfx=dfx.drop('z',1)
dfx=dfx.drop('color',1)
dfx=dfx.drop('clarity',1)
dfx=dfx.drop('cut',1)
dfx=dfx.drop('depth',1)

In [ ]:
dfx.rename(columns = {'carat1':'carat'}, inplace = True)
dfx.rename(columns = {'color1':'color'}, inplace = True)
dfx.rename(columns = {'table1':'table'}, inplace = True)
dfx.rename(columns = {'x1':'x'}, inplace = True)
dfx.rename(columns = {'y1':'y'}, inplace = True)
dfx.rename(columns = {'z1':'z'}, inplace = True)
dfx.rename(columns = {'clarity1':'carat'}, inplace = True)
dfx.rename(columns = {'cut1':'carat'}, inplace = True)
dfx.rename(columns = {'depth1':'carat'}, inplace = True)

In [ ]:
print(dfx)

          carat     table         x  ...     carat     carat     carat
0     -1.198157 -1.099662 -1.587823  ... -0.484260 -0.538094 -0.174090
1     -1.240350  1.585514 -1.641310  ... -1.064107  0.434945 -1.360726
2     -1.198157  3.375631 -1.498677  ...  0.095588 -1.511133 -3.384987
3     -1.071577  0.242926 -1.364959  ...  0.675435  0.434945  0.454129
4     -1.029384  0.242926 -1.240155  ... -0.484260 -1.511133  1.082348
...         ...       ...       ...  ...       ...       ...       ...
53935 -0.164426 -0.204603  0.016798  ... -1.064107 -0.538094 -0.662705
53936 -0.164426 -1.099662 -0.036690  ... -1.064107 -1.511133  0.942744
53937 -0.206619  1.137985 -0.063434  ... -1.064107  1.407985  0.733338
53938  0.130926  0.242926  0.373380  ... -0.484260  0.434945 -0.523100
53939 -0.101136 -1.099662  0.088114  ... -0.484260 -0.538094  0.314525

[53940 rows x 9 columns]


In [ ]:
import numpy as np

In [ ]:
X=dfx.to_numpy()
X

array([[-1.1981567 , -1.0996618 , -1.58782273, ..., -0.48425981,
        -0.53809398, -0.17408989],
       [-1.24034979,  1.58551401, -1.64131007, ..., -1.0641074 ,
         0.43494532, -1.36072587],
       [-1.1981567 ,  3.37563121, -1.49867716, ...,  0.09558778,
        -1.51113328, -3.38498725],
       ...,
       [-0.20661904,  1.13798471, -0.0634335 , ..., -1.0641074 ,
         1.40798462,  0.73333762],
       [ 0.1309257 ,  0.24292611,  0.37337979, ..., -0.48425981,
         0.43494532, -0.52310048],
       [-0.10113631, -1.0996618 ,  0.08811397, ..., -0.48425981,
        -0.53809398,  0.31452492]])

In [ ]:
y=dfy.to_numpy()
y

array([ 326,  326,  327, ..., 2757, 2757, 2757])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=55)

In [ ]:
m=X_train.shape[0]
m

43152

In [ ]:
import pickle
 


In [ ]:
"""def Eucledian(p,q):
  x=np.subtract(p,q)
  x1=x.dot(x)
  x=np.sqrt(x1)
  return x

def Manhattan(p,q):
  x=np.subtract(p,q)
  x1=abs(x)
  x=np.sum(x1)
  return x

# temp=Eucledian([1,5,10],[0,1,1])
# print(temp)
# temp1=Manhattan([1,5,10],[0,1,1])
# print(temp1)
k_val=[3,7,11,16]

for k in k_val:
  predicted_Eu=[]
  predicted_Man=[]
  for i in range(0,1000):
    test=X_test[i]
    dist_Eu=[]
    dist_Man=[]
    dist_Eu1=[]
    dist_Man1=[]
    for i in range(0,len(X_train)):
      dist_Eu.append([y_train[i],Eucledian(test,X_train[i])])
      dist_Man.append([y_train[i],Manhattan(test,X_train[i])])
    dist_Eu1 = sorted(dist_Eu, key=lambda x: x[1])
    dist_Man1 = sorted(dist_Man, key=lambda x: x[1])
    avg_eucledian=0
    avg_Manhattan=0
    for i in range(0,k):
      avg_eucledian+=(dist_Eu1[i][0])
      avg_Manhattan+=(dist_Man1[i][0])
    avg_eucledian=avg_eucledian/k
    avg_Manhattan=avg_Manhattan/k
    predicted_Eu.append(avg_eucledian)
    predicted_Man.append(avg_Manhattan)
  with open("Eucledian("+str(k)+").pkl", 'wb') as f:
    pickle.dump(predicted_Eu, f)
  with open("Manhattan("+str(k)+").pkl", 'wb') as f:
    pickle.dump(predicted_Man, f)
  print(len(predicted_Eu))
  print(len(predicted_Man))"""

'def Eucledian(p,q):\n  x=np.subtract(p,q)\n  x1=x.dot(x)\n  x=np.sqrt(x1)\n  return x\n\ndef Manhattan(p,q):\n  x=np.subtract(p,q)\n  x1=abs(x)\n  x=np.sum(x1)\n  return x\n\n# temp=Eucledian([1,5,10],[0,1,1])\n# print(temp)\n# temp1=Manhattan([1,5,10],[0,1,1])\n# print(temp1)\nk_val=[3,7,11,16]\n\nfor k in k_val:\n  predicted_Eu=[]\n  predicted_Man=[]\n  for i in range(0,1000):\n    test=X_test[i]\n    dist_Eu=[]\n    dist_Man=[]\n    dist_Eu1=[]\n    dist_Man1=[]\n    for i in range(0,len(X_train)):\n      dist_Eu.append([y_train[i],Eucledian(test,X_train[i])])\n      dist_Man.append([y_train[i],Manhattan(test,X_train[i])])\n    dist_Eu1 = sorted(dist_Eu, key=lambda x: x[1])\n    dist_Man1 = sorted(dist_Man, key=lambda x: x[1])\n    avg_eucledian=0\n    avg_Manhattan=0\n    for i in range(0,k):\n      avg_eucledian+=(dist_Eu1[i][0])\n      avg_Manhattan+=(dist_Man1[i][0])\n    avg_eucledian=avg_eucledian/k\n    avg_Manhattan=avg_Manhattan/k\n    predicted_Eu.append(avg_eucledian)\n 

In [ ]:
def load_from_pickle(filename):
  arr=[]
  with open(filename,'rb') as f:
    arr=pickle.load(f)
  return arr

In [ ]:
man=load_from_pickle("Manhattan(5).pkl")
euc=load_from_pickle("Eucledian(5).pkl")
print(man[:10])
print(euc[:10])
print(y_test[:10])

[1825.0, 8036.8, 5007.0, 2814.2, 2777.0, 653.8, 1496.0, 662.6, 8378.0, 11919.6]
[1858.8, 8620.4, 5707.4, 2678.6, 2777.0, 632.4, 1471.4, 662.6, 8338.8, 12260.0]
[ 1882  9586  5058  2780  2811   644  1378   552  7823 12800]


In [ ]:
temp=y_test.tolist()
temp=temp[:1000]
n=len(temp)

In [ ]:
def calculate_MSE(p,q,n):
  x=np.subtract(p,q)
  x1=x.dot(x)
  x=x1/n
  return x
mse=calculate_MSE(euc,temp,n)
print(mse)

913343.0797200003


In [ ]:
def calculate_MSE(p,q,n):
  x=np.subtract(p,q)
  x1=x.dot(x)
  x=x1/n
  return x
mse=calculate_MSE(man,temp,n)
print(mse)

810278.9822399999


In [ ]:
def calculate_MAE(p,q,n):
  x=np.subtract(p,q)
  x1=abs(x)
  x=np.sum(x1)
  x1=x/n
  return x1
mae=calculate_MAE(euc,temp,n)
print(mae)

443.63220000000007


In [ ]:
def calculate_MAE(p,q,n):
  x=np.subtract(p,q)
  x1=abs(x)
  x=np.sum(x1)
  x1=x/n
  return x1
mae=calculate_MAE(man,temp,n)
print(mae)

410.054


In [ ]:
def R2_score(a,b):
  x=np.subtract(a,b)
  x1=x.dot(x)
  n=len(a)
  sum=0
  for i in range(0,n):
    sum+=a[i]
  avg=sum/n
  mean=avg*np.ones(n)
  ans=np.subtract(b,mean)
  ans1=ans.dot(ans)
  R=1-(x1/ans1)
  return R
R2=R2_score(euc,temp)
print(R2)

0.9372703292427836


In [ ]:
def R2_score(a,b):
  x=np.subtract(a,b)
  x1=x.dot(x)
  n=len(a)
  sum=0
  for i in range(0,n):
    sum+=a[i]
  avg=sum/n
  mean=avg*np.ones(n)
  ans=np.subtract(b,mean)
  ans1=ans.dot(ans)
  R=1-(x1/ans1)
  return R
R2=R2_score(man,temp)
print(R2)


0.9443482705110914
